name: Test

on:
  pull_request:

jobs:
  macos:
    name: macOS
    runs-on: macos-14
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            vcpkg/downloads
            ~/.cache/vcpkg/archives
          key: vcpkg-macos-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'ports/**', 'triplets/**') }}
          restore-keys: |
            vcpkg-macos-

      - name: Install build tools
        run: brew install autoconf automake autoconf-archive libtool pkg-config ninja

      - name: Setup vcpkg
        run: ./scripts/setup_vcpkg.sh

      - name: Configure
        working-directory: desktop
        run: cmake --preset macos

      - name: Build
        working-directory: desktop
        run: cmake --build --preset default -t Strategr -t tests

      - name: Run core tests
        working-directory: desktop/build/core
        run: ctest --output-on-failure
